### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\xd7' in position 26: ordinal not in range(128)

### ISSUE THREAD

**Issue by byee4** [eleozzr/desc#15]
Hi, I've installed desc and am trying to run the basic tests. However I'm running into a small problem (I believe the training finishes successfully):
[pipfreeze_desc.txt](https://github.com/eleozzr/desc/files/3746020/pipfreeze_desc.txt)

```
delta_label  0.004814814814814815 < tol  0.005
Reached tolerance threshold. Stop training.
The final prediction cluster is:
0    1492
1    1208
dtype: int64
The desc has been trained successfully!!!!!!
The summary of desc model is:
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input (InputLayer)           (None, 100)               0         
_________________________________________________________________
encoder_0 (Dense)            (None, 64)                6464      
_________________________________________________________________
encoder_1 (Dense)            (None, 16)                1040      
_________________________________________________________________
clustering (ClusteringLayer) (None, 2)                 32        
=================================================================
Total params: 7,536
Trainable params: 7,536
Non-trainable params: 0
_________________________________________________________________
The runtime of (resolution=0.1)is: 45.76247525215149
The run time for all resolution is: 45.7717764377594
After training, the information of adata is:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/desc/tools/test.py", line 9, in run_desc_test
    adata = train(adata, dims=[100, 64, 16], louvain_resolution=0.1)
  File "/opt/conda/lib/python3.6/site-packages/desc/models/desc.py", line 330, in train
    print("After training, the information of adata is:\n",adata)
UnicodeEncodeError: 'ascii' codec can't encode character '\xd7' in position 26: ordinal not in range(128)
```

**Comment by eleozzr** [comment]
Thank you for pointing that, I will fix it as soon as possible.
