### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by manarai** [eleozzr/desc#8]
Hi,

I keep on having the following error when installing desc. Your help would be greatle appreciated.

>>> import platform
>>> platform.python_version()
'3.6.8'
>>> import tensorflow as tf
>>> tf.__version__
'1.7.0'
>>> import desc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tommy/desc/desc/__init__.py", line 2, in <module>
    from . import tools
  File "/Users/tommy/desc/desc/tools/__init__.py", line 1, in <module>
    from anndata import read_h5ad
ImportError: cannot import name 'read_h5ad'

**Comment by manarai** [comment]
I just figure it out!
